<Bx.Card>
    <Bx.Card.Header 
        title="${1:Title}" 
        subTitle="${2:SubTitle}"/>
    <Bx.Card.Content>
        <p>
            ${1:Title} + ${2:SubTitle}
        </p>
    </Bx.Card.Content>
    <Bx.Card.Actions>
        <Bx.Button 
            primary>
            ${3:PrimaryAction}
        </Bx.Button>
        <Bx.Button 
            accent 
            flat>
            ${4:SecondaryAction}
        </Bx.Button>
    </Bx.Card.Actions>
</Bx.Card>